import type { Metadata } from "next";
import { Inter, Roboto, Bungee_Spice } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], display: "swap" });

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

const bungee_spice = Bungee_Spice({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "This is a default Next-js Title",
    template: "%s | Codevolution ",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={bungee_spice.className}>
        <header
          style={{
            background: "indigo",
            padding: "1rem",
            color: "#fff",
          }}
        >
          <p>Header area</p>
        </header>

        <section
          style={{
            padding: "2rem 4em",
          }}
        >
          {children}
        </section>

        <footer
          style={{
            background: "crimson",
            padding: "1rem",
            color: "#fff",
          }}
        >
          <p>Footer area</p>
        </footer>
      </body>
    </html>
  );
}
